### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by stevemao**
I was testing the new release and found more failing tests (two of the added).

### CODE REVIEW

**Comment by sindresorhus** [comment]
Excellent. Yes, your approach is definitely better.

**Comment by stevemao** [comment]
Thanks :) I originally used `clone` for some reason and realised there is no reason to use it after I saw your release :)

**Comment by sindresorhus** [comment]
@stevemao Does https://github.com/sindresorhus/sort-on/commit/e63c03ecfce67d696282679b26d575f8a23e14e6 lgty?

**Comment by sindresorhus** [comment]
@arthurvr done.

**Comment by stevemao** [comment]
I think so... When I wrote this I had a feeling it could be simpler but couldn't see it at the time :p

**Pull request merged**
